### ISSUE TITLE
查询失败

### ISSUE THREAD

**Issue by lionty** [SJTU-IPADS/wukong#10]
您好，我执行SPARQL查询的时候报错了。我使用的sparql查询是wukong-master/scripts/sparql_query/lubm里面提供的查询语句。数据集的生成也是按照安装教程中的步骤生成的。希望您有空的时候可以回答一下。谢谢！
<img width="1162" alt="屏幕快照 2019-11-04 09 35 40" src="https://user-images.githubusercontent.com/34648301/68095694-a246e880-fee6-11e9-8757-43f721c0fc89.png">

**Comment by realstolz** [comment]
please use config -v to show the current setting. 

The SPARQL queries under sparql_query folder need to enable the planner to generate the execute plan automatically. 

The SPARQL queries under query folder should disable the planner, since then have embedded the execution plan into the queries with some specific grammar (e.g., <).
