### ISSUE TITLE
Is Wukong+G available now?

### ISSUE THREAD

**Issue by bookug** [SJTU-IPADS/wukong#8]
Wukong+G, the paper titled "Fast and Concurrent RDF Queries using RDMA-assisted GPU Graph Exploration".

**Comment by realstolz** [comment]
We do plan to release Wukong v0.2, which will include the first version of GPU support. But, we still need about one more month.

**Comment by bookug** [comment]
what is the main contribution on GPU? I mean, not the ideas on distributed computing or CPU-GPU cooperating, but only the accelerating methods on GPU?
Can Wukong+G support subgraph isomorphism? If not, how can I extend it?

**Comment by realstolz** [comment]
The new version (v0.2.0) has included our GPU extension.

First, we just try to use GPU to accelerate SPARQL queries, which are not typical GPU-friendly workloads.  Second, the main improvements (throughput) are due to performance isolation by using both CPU and GPU for hybrid workload (see our Wukong+G paper).

Currently, Wukong does not support subgraph isomorphism. You need translate them into SPARQL queries manually if possible.
